openapi: 3.0.3
info:
  version: 1.0.0
  title: Water Tracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of water tracker
tags:
  - name: Water
    description: Water usage data operations.
  - name: Auth
    description: Authentication and password reset operations.
servers:
  - url: https://water-tracker-backend-guwj.onrender.com
    description: Production server
  - url: http://127.0.0.1:3000
    description: Development server
paths:
  /auth/register:
    post:
      $ref: ../swagger/path/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml
  /auth/update-user:
    patch:
      $ref: ../swagger/path/auth/update-user.yaml
  /auth/google-login:
    post:
      $ref: ../swagger/path/auth/google-login.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/path/auth/send-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/path/auth/reset-pwd.yaml
  /water:
    post:
      $ref: ../swagger/path/water/post.yaml
  /water/{cardId}:
    patch:
      $ref: ../swagger/path/water/{cardId}/patch.yaml
    delete:
      $ref: ../swagger/path/water/{cardId}/delete.yaml
  /water/day:
    get:
      $ref: ../swagger/path/water/get-day.yaml
  /water/month:
    get:
      $ref: ../swagger/path/water/get-month.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
